#!/bin/bash

#change the vivado_path to yours if required.
modelsim_path=/opt/modelsim/modelsim_ase/bin
tb_tcl_file_name=rom_distributed_tb.tcl

$modelsim_path/vsim modelsim.ini -do $tb_tcl_file_name
